title: Chris Buckley
description: A Slack slash handler to output live departure boards from National Rail feeds.

url: https://cmbuckley.co.uk
baseurl: /slack-slash-trains

repository: cmbuckley/slack-slash-trains
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: /
 - title: CV
   url: /cv/
 - title: Contact
   url: /contact/
 - title: Blog
   url: /blog/
 - title: Interests
   url: /interests/
 - title: Projects
   url: /projects/

social:
   hackerone: cmbuckley
   github:    cmbuckley
   linkedin:  cmbuckley
   email:     chris@cmbuckley.co.uk
   twitter:   _cmbuckley
   facebook:  cmbuckley
   instagram: c.m.buckley
   amazon:    https://bux.re/amzn
