name: Deploy Jekyll site to Pages
on:
  push:
    branches: gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  pages:
    uses: cmbuckley/.github/.github/workflows/pages.yml@main
    secrets: inherit
